apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: suo4f4pm6-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: suo4f4pm6-python 
  name: suo4f4pm6-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: suo4f4pm6-python 
